"""The turn lifecycle: user message in, grounded answer out.

Stage order and the reasoning behind it are in ARCHITECTURE.md section 4. The
two decisions worth restating here:

1. Answerability, ambiguity and generation are one model call, not three. On an
   8 GB laptop each call costs seconds of wall clock, and a model that can
   write the SQL is already deciding whether the SQL is writable.

2. The repair loop feeds the model the exact validator or database error. A 7B
   model corrects a named error ("column 'yield_kg' does not exist; crop_cycle
   has: ...") far more reliably than it corrects an instruction to try again.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any

from server.catalog import Catalog
from server.config import Settings
from server.context.prompts import load as load_prompt, versions as prompt_versions
from server.conversation.state import ConversationState, ConversationStore, Intent
from server.model.client import Completion, LlamaCppClient, ModelError
from server.model.schemas import CLASSIFY_INTENT_SCHEMA, GENERATE_SQL_SCHEMA
from server.sql.executor import Executor, ExecutionError, ResultSet
from server.sql.validator import ValidationError, validate

# Temperature per generation attempt. The first pass is greedy for
# determinism; retries escalate because at temperature 0 a regeneration with a
# near-identical prompt reproduces the same tokens, so a bounded retry loop
# that never varies sampling explores nothing and simply burns the budget.
# Observed directly: a malformed CAST was regenerated byte-identically three
# times before this was added.
REPAIR_TEMPERATURES = (0.0, 0.35, 0.7)

INJECTION_MARKERS = (
    "ignore previous", "ignore the above", "disregard previous",
    "system prompt", "you are now", "new instructions:",
)


@dataclass
class Attempt:
    sql: str
    verdict: str            # ok | validation_error | execution_error
    error_code: str | None = None
    error: str | None = None


@dataclass
class TurnResult:
    conversation_id: str
    turn_index: int
    question: str
    resolved_question: str
    intent: str
    action: str                              # answer | refuse | clarify | error
    answer: str = ""
    sql: str | None = None
    assumptions: list[str] = field(default_factory=list)
    result: ResultSet | None = None
    attempts: list[Attempt] = field(default_factory=list)
    coverage_note: str | None = None
    warnings: list[str] = field(default_factory=list)
    timings_ms: dict[str, int] = field(default_factory=dict)
    tokens: dict[str, int] = field(default_factory=dict)
    state: dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> dict[str, Any]:
        payload = {
            "conversation_id": self.conversation_id,
            "turn_index": self.turn_index,
            "question": self.question,
            "resolved_question": self.resolved_question,
            "intent": self.intent,
            "action": self.action,
            "answer": self.answer,
            "sql": self.sql,
            "assumptions": self.assumptions,
            "attempts": len(self.attempts),
            "attempt_detail": [a.__dict__ for a in self.attempts],
            "retried": len(self.attempts) > 1,
            "coverage_note": self.coverage_note,
            "warnings": self.warnings,
            "timings_ms": self.timings_ms,
            "tokens": self.tokens,
            "state": self.state,
        }
        payload.update(
            self.result.to_json() if self.result
            else {"columns": [], "rows": [], "row_count": 0, "truncated": False}
        )
        return payload


class Pipeline:
    """Turn lifecycle. See ARCHITECTURE.md section 4."""

    def __init__(
        self,
        *,
        catalog: Catalog,
        model: LlamaCppClient,
        executor: Executor,
        store: ConversationStore,
        settings: Settings,
        audit=None,
    ) -> None:
        self.catalog = catalog
        self.model = model
        self.executor = executor
        self.store = store
        self.settings = settings
        self.audit = audit

    def _tag(self, stage: str, state=None, attempt: int = 0) -> None:
        """Label the next model call so its transcript row is attributable."""
        context = getattr(self.model, "context", None)
        if context is None:
            return
        context.update({
            "stage": stage,
            "attempt": attempt,
            "conversation_id": getattr(state, "conversation_id", None),
            "turn": getattr(state, "turn_index", None),
        })

    # ------------------------------------------------------------------ entry --
    def ask(self, message: str, conversation_id: str | None = None) -> TurnResult:
        state = self.store.get(conversation_id)
        timings: dict[str, int] = {}
        tokens = {"prompt": 0, "completion": 0}

        guard_error = self._guard(message)
        turn = state.begin_turn(message)
        if guard_error:
            # A guard that fires is the system declining deliberately, not
            # malfunctioning. "error" would badge a working guardrail as a bug
            # in the UI and invite the user to retry.
            turn.action = "refuse"
            return self._finish(
                TurnResult(
                    conversation_id=state.conversation_id,
                    turn_index=turn.index,
                    question=message,
                    resolved_question=message,
                    intent="META",
                    action="refuse",
                    answer=guard_error,
                    state=state.to_json(),
                ),
                state,
            )

        # A pending clarification makes this turn the answer to it, not a new
        # question. Folding it in here is what stops the agent asking twice.
        resolved_message = message
        if state.pending_clarification is not None:
            merged = state.resolve_clarification(message)
            if merged:
                resolved_message = merged

        intent, intent_completion = self._classify(state, resolved_message, timings)
        _accumulate(tokens, intent_completion)
        turn.intent = intent
        policy = state.apply_intent(intent)

        generated, gen_completion = self._generate(
            state, resolved_message, policy, timings
        )
        _accumulate(tokens, gen_completion)

        action = generated.get("action", "sql")
        if action == "refuse":
            return self._refuse(state, turn, message, resolved_message, intent,
                                generated, timings, tokens)
        if action == "clarify":
            return self._clarify(state, turn, message, resolved_message, intent,
                                 generated, timings, tokens)

        return self._answer(state, turn, message, resolved_message, intent,
                            generated, policy, timings, tokens)

    # ------------------------------------------------------------------ guard --
    def _guard(self, message: str) -> str | None:
        text = (message or "").strip()
        if not text:
            return "Please type a question."
        if len(text) > self.settings.max_question_chars:
            return (
                f"That question is {len(text)} characters; the limit is "
                f"{self.settings.max_question_chars}. Please shorten it."
            )
        lowered = text.lower()
        if any(marker in lowered for marker in INJECTION_MARKERS):
            return (
                "That message looks like an attempt to change how I work rather "
                "than a question about the data. Ask me about farmers, plots, "
                "crop cycles, sensor readings, advisories, agents or visits."
            )
        return None

    # --------------------------------------------------------------- classify --
    def _classify(
        self, state: ConversationState, message: str, timings: dict[str, int]
    ) -> tuple[Intent, Completion | None]:
        # The first turn cannot be a continuation, so the call is skipped. This
        # is the single cheapest latency win in the pipeline.
        if len(state.turns) <= 1:
            timings["classify"] = 0
            return "NEW_TOPIC", None

        prompt = load_prompt("classify_intent")
        rendered = prompt.render(
            history=state.history_block(),
            state_summary=state.state_summary(),
            message=message,
        )
        self._tag("classify", state)
        started = time.perf_counter()
        try:
            completion = self.model.complete(
                system="You classify conversational turns. Reply with JSON only.",
                user=rendered,
                json_schema=CLASSIFY_INTENT_SCHEMA,
                max_tokens=120,
            )
            intent = completion.json().get("intent", "NEW_TOPIC")
        except (ModelError, ValueError):
            # Losing the classifier must not lose the turn. NEW_TOPIC is the
            # safe default: it discards context rather than leaking it.
            timings["classify"] = int((time.perf_counter() - started) * 1000)
            return "NEW_TOPIC", None

        timings["classify"] = int((time.perf_counter() - started) * 1000)
        return intent, completion

    # --------------------------------------------------------------- generate --
    def _context(self, state: ConversationState, message: str, policy: dict) -> str:
        parts = []
        if policy["show_history"]:
            parts.append("# Conversation so far\n\n" + state.history_block())
            summary = state.state_summary()
            if summary:
                parts.append("# Carried forward from the previous query\n\n" + summary)
            if state.last_sql and policy["amend"]:
                parts.append(
                    "# Previous SQL\n\nAmend this query rather than starting "
                    "over, unless the new message changes the subject:\n\n"
                    + state.last_sql
                )
        clarifications = state.clarifications_block()
        if clarifications:
            parts.append("# Settled earlier\n\n" + clarifications)
        parts.append("# The question to answer now\n\n" + message)
        return "\n\n".join(parts)

    def _system_prompt(self) -> str:
        prompt = load_prompt("generate_sql")
        examples = load_prompt("generate_sql_examples")
        return (
            prompt.render(
                schema=self.catalog.render_schema(),
                keys=self.catalog.render_keys(),
                rules=self.catalog.render_rules(),
                coverage=self.catalog.render_coverage(),
                today=time.strftime("%Y-%m-%d"),
                latest_observation=self.catalog.latest_observation_date,
            )
            + "\n\n# Examples\n\n"
            + examples.body.strip()
        )

    def _generate(
        self,
        state: ConversationState,
        message: str,
        policy: dict,
        timings: dict[str, int],
        repair_note: str | None = None,
        attempt: int = 0,
    ) -> tuple[dict[str, Any], Completion | None]:
        user = self._context(state, message, policy)
        if repair_note:
            user += "\n\n# Your previous attempt failed\n\n" + repair_note

        temperature = REPAIR_TEMPERATURES[min(attempt, len(REPAIR_TEMPERATURES) - 1)]
        self._tag("generate", state, attempt=attempt)
        started = time.perf_counter()
        try:
            completion = self.model.complete(
                system=self._system_prompt(),
                user=user,
                json_schema=GENERATE_SQL_SCHEMA,
                max_tokens=700,
                temperature=temperature,
            )
            payload = completion.json()
        except (ModelError, ValueError) as exc:
            timings["generate"] = timings.get("generate", 0) + int(
                (time.perf_counter() - started) * 1000
            )
            return (
                {"action": "refuse",
                 "reason": f"The model did not return a usable answer ({exc})."},
                None,
            )

        timings["generate"] = timings.get("generate", 0) + int(
            (time.perf_counter() - started) * 1000
        )
        return payload, completion

    # ---------------------------------------------------------------- outcomes --
    def _refuse(self, state, turn, question, resolved, intent, generated,
                timings, tokens) -> TurnResult:
        turn.action = "refuse"
        turn.answer = generated.get("reason", "I cannot answer that from this data.")
        return self._finish(
            TurnResult(
                conversation_id=state.conversation_id,
                turn_index=turn.index,
                question=question,
                resolved_question=resolved,
                intent=intent,
                action="refuse",
                answer=turn.answer,
                timings_ms=timings,
                tokens=tokens,
                state=state.to_json(),
            ),
            state,
        )

    def _clarify(self, state, turn, question, resolved, intent, generated,
                 timings, tokens) -> TurnResult:
        ask = generated.get("question") or "Could you be more specific?"
        state.ask_clarification(ask, resolved)
        turn.action = "clarify"
        turn.answer = ask
        return self._finish(
            TurnResult(
                conversation_id=state.conversation_id,
                turn_index=turn.index,
                question=question,
                resolved_question=resolved,
                intent=intent,
                action="clarify",
                answer=ask,
                timings_ms=timings,
                tokens=tokens,
                state=state.to_json(),
            ),
            state,
        )

    def _answer(self, state, turn, question, resolved, intent, generated,
                policy, timings, tokens) -> TurnResult:
        attempts: list[Attempt] = []
        result: ResultSet | None = None
        validated_sql: str | None = None
        assumptions = list(generated.get("assumptions", []))
        payload = generated

        for attempt_no in range(self.settings.max_repair_attempts + 1):
            sql = (payload.get("sql") or "").strip()
            try:
                checked = validate(sql, self.catalog)
            except ValidationError as exc:
                attempts.append(Attempt(sql, "validation_error", exc.code, exc.message))
                repair = _repair_note(sql, exc.message)
            else:
                started = time.perf_counter()
                try:
                    result = self.executor.run(checked.sql)
                except ExecutionError as exc:
                    attempts.append(
                        Attempt(checked.sql, "execution_error", exc.code, exc.message)
                    )
                    repair = _repair_note(checked.sql, exc.message)
                else:
                    timings["execute"] = int((time.perf_counter() - started) * 1000)
                    attempts.append(Attempt(checked.sql, "ok"))
                    validated_sql = checked.sql
                    break

            if attempt_no == self.settings.max_repair_attempts:
                break
            payload, completion = self._generate(
                state, resolved, policy, timings,
                repair_note=repair, attempt=attempt_no + 1,
            )
            _accumulate(tokens, completion)
            assumptions = list(payload.get("assumptions", assumptions))
            if payload.get("action") == "refuse":
                return self._refuse(state, turn, question, resolved, intent,
                                    payload, timings, tokens)

        if validated_sql is None or result is None:
            last = attempts[-1] if attempts else None
            turn.action = "error"
            turn.attempts = len(attempts)
            message = (
                "I could not produce a working query for that, even after "
                f"{len(attempts)} attempts. "
                + (f"The last problem was: {last.error}" if last and last.error else "")
            )
            return self._finish(
                TurnResult(
                    conversation_id=state.conversation_id,
                    turn_index=turn.index,
                    question=question,
                    resolved_question=resolved,
                    intent=intent,
                    action="error",
                    answer=message,
                    sql=last.sql if last else None,
                    attempts=attempts,
                    timings_ms=timings,
                    tokens=tokens,
                    state=state.to_json(),
                ),
                state,
            )

        state.record_sql(validated_sql)
        coverage_note = self._coverage_note(result, validated_sql)
        answer, narrate_completion = self._narrate(
            resolved, validated_sql, assumptions, result, coverage_note, timings
        )
        _accumulate(tokens, narrate_completion)

        turn.action = "answer"
        turn.sql = validated_sql
        turn.row_count = result.row_count
        turn.answer = answer
        turn.attempts = len(attempts)

        return self._finish(
            TurnResult(
                conversation_id=state.conversation_id,
                turn_index=turn.index,
                question=question,
                resolved_question=resolved,
                intent=intent,
                action="answer",
                answer=answer,
                sql=validated_sql,
                assumptions=assumptions,
                result=result,
                attempts=attempts,
                coverage_note=coverage_note,
                timings_ms=timings,
                tokens=tokens,
                state=state.to_json(),
            ),
            state,
        )

    # ---------------------------------------------------------------- narrate --
    def _coverage_note(self, result: ResultSet, sql: str) -> str | None:
        """Explain an empty result caused by the data ending before the period
        asked about, instead of reporting it as 'there were none'."""
        if result.row_count > 0:
            return None
        lowered = sql.lower()
        if not any(tok in lowered for tok in ("date", "_at", "interval", "now()",
                                              "current_date", "extract")):
            return None
        return (
            "The result is empty and the query filtered on a date. The data "
            f"ends on {self.catalog.latest_observation_date}; sensor readings "
            "stop earlier still, on "
            f"{self.catalog.raw['data_coverage']['sensor_reading.recorded_at']['max'][:10]}. "
            "Say that the period asked about is outside the data rather than "
            "saying there were none."
        )

    def _narrate(self, question, sql, assumptions, result, coverage_note, timings):
        prompt = load_prompt("narrate")
        rendered = prompt.render(
            question=question,
            sql=sql,
            assumptions="\n".join(f"- {a}" for a in assumptions) or "(none stated)",
            result_block=_result_block(result, self.settings.narrate_row_cap),
            coverage_note=coverage_note or "",
        )
        self._tag("narrate")
        started = time.perf_counter()
        try:
            completion = self.model.complete(
                system="You explain query results in plain English. No markdown.",
                user=rendered,
                max_tokens=280,
                temperature=0.2,
            )
            answer = completion.text.strip()
        except ModelError:
            timings["narrate"] = int((time.perf_counter() - started) * 1000)
            return (
                f"The query returned {result.row_count} rows. "
                "(The explanation step was unavailable.)",
                None,
            )
        timings["narrate"] = int((time.perf_counter() - started) * 1000)
        return answer, completion

    # ----------------------------------------------------------------- finish --
    def _finish(self, outcome: TurnResult, state: ConversationState) -> TurnResult:
        outcome.state = state.to_json()
        outcome.timings_ms["total"] = sum(
            v for k, v in outcome.timings_ms.items() if k != "total"
        )
        if self.audit:
            self.audit.write({
                "conversation_id": outcome.conversation_id,
                "turn": outcome.turn_index,
                "question": outcome.question,
                "resolved_question": outcome.resolved_question,
                "intent": outcome.intent,
                "action": outcome.action,
                "sql": outcome.sql,
                "row_count": outcome.result.row_count if outcome.result else 0,
                "attempts": [a.__dict__ for a in outcome.attempts],
                "timings_ms": outcome.timings_ms,
                "tokens": outcome.tokens,
                "model": self.model.model_id,
                "prompt_versions": prompt_versions(),
                "catalog_version": self.catalog.version,
            })
        return outcome


# ------------------------------------------------------------------- helpers --
def _accumulate(tokens: dict[str, int], completion: Completion | None) -> None:
    if completion is None:
        return
    tokens["prompt"] += completion.prompt_tokens
    tokens["completion"] += completion.completion_tokens


def _repair_note(sql: str, error: str) -> str:
    return (
        f"This SQL was rejected:\n\n{sql}\n\nReason: {error}\n\n"
        "Fix the specific problem named above and return the corrected query. "
        "If the data genuinely cannot answer the question, return action "
        '"refuse" instead of guessing at column names.'
    )


def _result_block(result: ResultSet, row_cap: int) -> str:
    if result.row_count == 0:
        return "(no rows)"
    header = " | ".join(c.name for c in result.columns)
    lines = [header, "-" * len(header)]
    for row in result.rows[:row_cap]:
        lines.append(" | ".join("NULL" if v is None else str(v) for v in row))
    if result.row_count > row_cap:
        lines.append(f"... {result.row_count - row_cap} more rows not shown")
    return "\n".join(lines)
